# Generated by Django 4.2.6 on 2023-11-01 12:25

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=model_utils.fields.StatusField(choices=[('staff', 'staff'), ('subscriber', 'subscriber'), ('creator', 'creator')], default='subscriber', max_length=100, no_check_for_status=True, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
        ),
    ]
