# Generated by Django 4.2.6 on 2023-11-01 15:52

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_type_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=model_utils.fields.StatusField(choices=[('user', 'user'), ('creator', 'creator')], default='subscriber', max_length=100, no_check_for_status=True, verbose_name='User Type'),
        ),
    ]
